### ISSUE TITLE
Please update the examples

### ISSUE THREAD

**Issue by cornfeedhobo** [rexray/gocsi#156]
The examples that exist in the organization are very old. Could someone pleas bring them up-to-date with this tool?

**Comment by cornfeedhobo** [comment]
Update: nevermind. the folks at k8s-sig have informed me they are deprecating all use of this library.

**Comment by sujeet01** [comment]
> 

@cornfeedhobo Were they able to suggest any alternative libraries?

**Comment by cornfeedhobo** [comment]
@sujeet01 no, this library was deprecated. I gave up.
