### ISSUE TITLE
i18n: Support for non-English speaking contributors

### ISSUE THREAD

**Issue by LuigiBaute** [rexray/gocsi#92]
hello, I would like to collaborate with your project living from translator to Spanish which is my native language

**Comment by akutz** [comment]
Hi @LuigiBaute,

We welcome contributions from people no matter where they live. I understand that English is not your native language, and while we will do our best to accommodate you, there may be some challenges. Could you possibly use Google Translate to provide a bulleted list of your ideas/suggestions?

---

Hola Luigi,

Recibimos contribuciones de personas sin importar dónde vivan. Entiendo que el inglés no es su lengua materna, y si bien haremos nuestro mejor esfuerzo para complacerlo, puede haber algunos desafíos. ¿Podría usar Google Translate (https://translate.google.com) para proporcionar una lista con viñetas de sus ideas / sugerencias?

**Comment by LuigiBaute** [comment]
Yes i'm able to work with Google Translate if needed.
